import { Product } from '../../src/frontend/src/data/products';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-chord-hugo-tt2',
    product_id: 'prod-chord-hugo-tt2',
    categoryId: 'dacs',
    category_id: 'dacs',
    brand: 'Chord Electronics',
    model: 'Hugo TT 2',
    nameEn: 'Chord Hugo TT 2 DAC/Headphone Amp',
    nameZh: 'Chord Hugo TT 2 解碼/耳擴/前級',
    name_en: 'Chord Hugo TT 2 DAC/Headphone Amp',
    name_zh: 'Chord Hugo TT 2 解碼/耳擴/前級',
    priceHkd: 39800,
    price_hkd: 39800,
    descriptionEn: 'Advanced DAC',
    descriptionZh: '進階解碼耳擴',
    description_en: 'Advanced DAC',
    description_zh: '進階解碼耳擴',
    acousticSignatureEn: 'Neutral',
    acousticSignatureZh: '中性',
    acoustic_signature_en: 'Neutral',
    acoustic_signature_zh: '中性',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    tags: ['FPGA Filter'],
    interfaces: ['XLR', 'BNC', 'USB']
  },
  {
    id: 'prod-sennheiser-hd800s',
    product_id: 'prod-sennheiser-hd800s',
    categoryId: 'head-fi',
    category_id: 'head-fi',
    brand: 'Sennheiser',
    model: 'HD 800 S',
    nameEn: 'Sennheiser HD 800 S Reference Open-Back Headphones',
    nameZh: 'Sennheiser HD 800 S 參考級開放式頭戴耳機',
    name_en: 'Sennheiser HD 800 S Reference Open-Back Headphones',
    name_zh: 'Sennheiser HD 800 S 參考級開放式頭戴耳機',
    priceHkd: 14200,
    price_hkd: 14200,
    descriptionEn: 'Flagship reference headphones',
    descriptionZh: '旗艦參考級耳機',
    description_en: 'Flagship reference headphones',
    description_zh: '旗艦參考級耳機',
    acousticSignatureEn: 'Wide soundstage',
    acousticSignatureZh: '寬廣音場',
    acoustic_signature_en: 'Wide soundstage',
    acoustic_signature_zh: '寬廣音場',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    tags: ['High-Impedance'],
    interfaces: ['XLR', '6.35mm'],
    impedance: 300
  },
  {
    id: 'prod-feliks-envy',
    product_id: 'prod-feliks-envy',
    categoryId: 'head-fi-amp',
    category_id: 'head-fi-amp',
    brand: 'Feliks Audio',
    model: 'Envy',
    nameEn: 'Feliks Audio Envy 300B Tube Amp',
    nameZh: 'Feliks Audio Envy 300B 旗艦膽機',
    name_en: 'Feliks Audio Envy 300B Tube Amp',
    name_zh: 'Feliks Audio Envy 300B 旗艦膽機',
    priceHkd: 58000,
    price_hkd: 58000,
    descriptionEn: 'Flagship 300B headphone tube amplifier',
    descriptionZh: '旗艦300B耳機膽機',
    description_en: 'Flagship 300B headphone tube amplifier',
    description_zh: '旗艦300B耳機膽機',
    acousticSignatureEn: 'Lush tube sound',
    acousticSignatureZh: '濃郁真空管音色',
    acoustic_signature_en: 'Lush tube sound',
    acoustic_signature_zh: '濃郁真空管音色',
    imageUrl: '',
    image_url: '',
    tags: ['Vacuum Tube 膽機', '300B Tube'],
    interfaces: ['XLR', '6.35mm'],
    isTube: true
  },
  {
    id: 'prod-eversolo-dmp-a8',
    product_id: 'prod-eversolo-dmp-a8',
    categoryId: 'streamers',
    category_id: 'streamers',
    brand: 'Eversolo',
    model: 'DMP-A8',
    nameEn: 'Eversolo DMP-A8 Streamer',
    nameZh: 'Eversolo DMP-A8 網絡播放器',
    name_en: 'Eversolo DMP-A8 Streamer',
    name_zh: 'Eversolo DMP-A8 網絡播放器',
    priceHkd: 15800,
    price_hkd: 15800,
    descriptionEn: 'High-res streamer',
    descriptionZh: '高解析度網絡播放器',
    description_en: 'High-res streamer',
    description_zh: '高解析度網絡播放器',
    acousticSignatureEn: 'Detailed',
    acousticSignatureZh: '細緻',
    acoustic_signature_en: 'Detailed',
    acoustic_signature_zh: '細緻',
    imageUrl: '',
    image_url: '',
    tags: ['I2S Digital Out'],
    interfaces: ['I2S', 'XLR', 'USB']
  },
  {
    id: 'prod-denafrips-venus-ii',
    product_id: 'prod-denafrips-venus-ii',
    categoryId: 'dacs',
    category_id: 'dacs',
    brand: 'Denafrips',
    model: 'Venus II',
    nameEn: 'Denafrips Venus II R-2R DAC',
    nameZh: 'Denafrips Venus II R-2R 解碼器',
    name_en: 'Denafrips Venus II R-2R DAC',
    name_zh: 'Denafrips Venus II R-2R 解碼器',
    priceHkd: 24800,
    price_hkd: 24800,
    descriptionEn: 'R-2R Ladder DAC',
    descriptionZh: 'R-2R 梯陣解碼器',
    description_en: 'R-2R Ladder DAC',
    description_zh: 'R-2R 梯陣解碼器',
    acousticSignatureEn: 'Analog warm',
    acousticSignatureZh: '模擬溫暖',
    acoustic_signature_en: 'Analog warm',
    acoustic_signature_zh: '模擬溫暖',
    imageUrl: '',
    image_url: '',
    tags: ['R-2R Ladder'],
    interfaces: ['I2S', 'XLR', 'BNC']
  },
  {
    id: 'prod-mcintosh-ma8950',
    product_id: 'prod-mcintosh-ma8950',
    categoryId: 'amplifiers',
    category_id: 'amplifiers',
    brand: 'McIntosh',
    model: 'MA8950',
    nameEn: 'McIntosh MA8950 Integrated Amp',
    nameZh: 'McIntosh MA8950 合併式擴音機',
    name_en: 'McIntosh MA8950 Integrated Amp',
    name_zh: 'McIntosh MA8950 合併式擴音機',
    priceHkd: 78000,
    price_hkd: 78000,
    descriptionEn: '200W Autoformer integrated amplifier',
    descriptionZh: '200W Autoformer 合併式擴音機',
    description_en: '200W Autoformer integrated amplifier',
    description_zh: '200W Autoformer 合併式擴音機',
    acousticSignatureEn: 'Dynamic power',
    acousticSignatureZh: '強勁動態',
    acoustic_signature_en: 'Dynamic power',
    acoustic_signature_zh: '強勁動態',
    imageUrl: '',
    image_url: '',
    tags: ['Autoformer'],
    interfaces: ['XLR', 'RCA']
  },
  {
    id: 'prod-bw-804-d4',
    product_id: 'prod-bw-804-d4',
    categoryId: 'loudspeakers',
    category_id: 'loudspeakers',
    brand: 'Bowers & Wilkins',
    model: '804 D4',
    nameEn: 'B&W 804 D4 Loudspeakers',
    nameZh: 'B&W 804 D4 鑽石高音落地喇叭',
    name_en: 'B&W 804 D4 Loudspeakers',
    name_zh: 'B&W 804 D4 鑽石高音落地喇叭',
    priceHkd: 108000,
    price_hkd: 108000,
    descriptionEn: 'Diamond dome tweeter floorstander',
    descriptionZh: '鑽石高音落地式喇叭',
    description_en: 'Diamond dome tweeter floorstander',
    description_zh: '鑽石高音落地式喇叭',
    acousticSignatureEn: 'Transparent precision',
    acousticSignatureZh: '通透精準',
    acoustic_signature_en: 'Transparent precision',
    acoustic_signature_zh: '通透精準',
    imageUrl: '',
    image_url: '',
    tags: ['Diamond Tweeter'],
    interfaces: ['Binding Post']
  },
  {
    id: 'prod-topping-d90-iii',
    product_id: 'prod-topping-d90-iii',
    categoryId: 'dacs',
    category_id: 'dacs',
    brand: 'Topping',
    model: 'D90 III',
    nameEn: 'Topping D90 III DAC',
    nameZh: 'Topping D90 III 解碼器',
    name_en: 'Topping D90 III DAC',
    name_zh: 'Topping D90 III 解碼器',
    priceHkd: 7980,
    price_hkd: 7980,
    descriptionEn: 'Flagship ESS Sabre DAC',
    descriptionZh: '旗艦 ESS Sabre 解碼器',
    description_en: 'Flagship ESS Sabre DAC',
    description_zh: '旗艦 ESS Sabre 解碼器',
    acousticSignatureEn: 'Ultra clean',
    acousticSignatureZh: '超淨背景',
    acoustic_signature_en: 'Ultra clean',
    acoustic_signature_zh: '超淨背景',
    imageUrl: '',
    image_url: '',
    tags: ['ESS Sabre'],
    interfaces: ['XLR', 'RCA', 'USB']
  },
  {
    id: 'prod-wiim-pro-plus',
    product_id: 'prod-wiim-pro-plus',
    categoryId: 'streamers',
    category_id: 'streamers',
    brand: 'WiiM',
    model: 'Pro Plus',
    nameEn: 'WiiM Pro Plus Streamer',
    nameZh: 'WiiM Pro Plus 串流播放器',
    name_en: 'WiiM Pro Plus Streamer',
    name_zh: 'WiiM Pro Plus 串流播放器',
    priceHkd: 1880,
    price_hkd: 1880,
    descriptionEn: 'Compact streamer',
    descriptionZh: '小巧串流播放機',
    description_en: 'Compact streamer',
    description_zh: '小巧串流播放機',
    acousticSignatureEn: 'Balanced',
    acousticSignatureZh: '均衡',
    acoustic_signature_en: 'Balanced',
    acoustic_signature_zh: '均衡',
    imageUrl: '',
    image_url: '',
    tags: ['AirPlay 2'],
    interfaces: ['Optical', 'RCA']
  }
];
