-- =============================================================================
-- Hi-Fi Shop Demo Platform - Cloud Spanner DDL Schema
-- Script 01: Table Creation DDL
-- File: sql/01_create_tables.sql
-- Description: Creates core schema tables (Categories, Products, ProductSpecifications,
--              and ProductEmbeddings) using Google Cloud Spanner DDL dialect with
--              parent-child table interleaving.
-- Target DB: Google Cloud Spanner (GoogleSQL Dialect)
-- Author: Database Architect
-- Date: August 13, 2026
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Categories Table (Top-Level Entity)
-- Stores product taxonomy and localized hierarchy (en-US / zh-HK).
-- -----------------------------------------------------------------------------
CREATE TABLE Categories (
  category_id STRING(64) NOT NULL,
  name_en STRING(255) NOT NULL,
  name_zh STRING(255) NOT NULL,
  slug STRING(100) NOT NULL,
  description_en STRING(MAX),
  description_zh STRING(MAX),
  display_order INT64 NOT NULL,
  created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  updated_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (category_id);

-- -----------------------------------------------------------------------------
-- 2. Products Master Table (Top-Level Entity)
-- Primary entity representing audiophile hardware items with HKD pricing
-- and bilingual metadata.
-- -----------------------------------------------------------------------------
CREATE TABLE Products (
  product_id STRING(64) NOT NULL,
  category_id STRING(64) NOT NULL,
  brand STRING(128) NOT NULL,
  model STRING(128) NOT NULL,
  name_en STRING(255) NOT NULL,
  name_zh STRING(255) NOT NULL,
  price_hkd NUMERIC NOT NULL,
  description_en STRING(MAX),
  description_zh STRING(MAX),
  acoustic_signature_en STRING(MAX),
  acoustic_signature_zh STRING(MAX),
  image_url STRING(1024),
  is_active BOOL NOT NULL DEFAULT (true),
  search_tokens TOKENLIST AS (TOKENLIST_CONCAT([TOKENIZE_FULLTEXT(name_en), TOKENIZE_FULLTEXT(brand), TOKENIZE_FULLTEXT(model), TOKENIZE_FULLTEXT(category_id), TOKENIZE_FULLTEXT(description_en)])) HIDDEN,
  created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  updated_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  CONSTRAINT FK_Products_Categories FOREIGN KEY (category_id) REFERENCES Categories (category_id)
) PRIMARY KEY (product_id);

-- -----------------------------------------------------------------------------
-- 3. ProductSpecifications Table (Interleaved Child Entity)
-- Stores physical hardware interface specs (XLR, I2S, Tube, Impedance).
-- Interleaved in parent `Products` table to colocate child rows on the same
-- physical Spanner split for zero-network-hop query performance.
-- -----------------------------------------------------------------------------
CREATE TABLE ProductSpecifications (
  product_id STRING(64) NOT NULL,
  spec_key STRING(128) NOT NULL,
  spec_value_en STRING(512) NOT NULL,
  spec_value_zh STRING(512) NOT NULL,
  is_filter_facet BOOL NOT NULL DEFAULT (false),
  created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (product_id, spec_key),
  INTERLEAVE IN PARENT Products ON DELETE CASCADE;

-- -----------------------------------------------------------------------------
-- 4. ProductEmbeddings Table (Interleaved Child Entity)
-- Stores 768-dimensional dense vector embeddings generated by Vertex AI.
-- Interleaved in parent `Products` table to ensure transactional co-location
-- and efficient KNN vector search operations.
-- -----------------------------------------------------------------------------
CREATE TABLE ProductEmbeddings (
  product_id STRING(64) NOT NULL,
  embedding_provider STRING(64) NOT NULL,
  embedding_dimensions INT64 NOT NULL,
  embedding ARRAY<FLOAT64> NOT NULL,
  created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  updated_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)
) PRIMARY KEY (product_id),
  INTERLEAVE IN PARENT Products ON DELETE CASCADE;
